### ISSUE TITLE
Color Map Change After R Update

### ISSUE THREAD

**Issue by wiw4002** [thomasp85/scico#18]
I recently updated to R 4.3, and was using the colors in this package, but it appears to be doing something different now?

Here is the call to 'vik' before:

![image](https://github.com/thomasp85/scico/assets/52979604/a5f87e5a-5dc6-4490-81de-6de507e350d0)

Here is the color scale using 'vik' now:

![image](https://github.com/thomasp85/scico/assets/52979604/af54793e-c69d-4708-95f8-f5bf42a1e228)

Here is the call to 'vikO' for reference:

![image](https://github.com/thomasp85/scico/assets/52979604/1e7b464e-aca4-4a7b-a978-f0abaed5e3e5)

They look less distinct than before? I ran the example under the ggplot support section, and got this when using 'vik':

![image](https://github.com/thomasp85/scico/assets/52979604/ad55512c-8c2f-4e27-834e-6aef5171aeb5)

**Comment by Crameri** [comment]
HiThanks for the message. I can jump in here: That’s just the old version (more brownish; version 4) and the new version (more reddish, versions >4) of vik. I adjusted it to be more reddish due to user requests.So, nothing wrong with scico, just the different colour map versions.Sorry, for the confusion!Fabio______________________________________________

Fabio Crameri · @fcrameri
Undertone.design
www.fabiocrameri.chAm 23/06/2023 um 21:35 schrieb wiw4002 ***@***.***>:﻿
I recently updated to R 4.3, and was using the colors in this package, but it appears to be doing something different now?
Here is the call to 'vik' before:

Here is the color scale using 'vik' now:

Here is the call to 'vikO' for reference:

They look less distinct than before? I ran the example under the ggplot support section, and got this when using 'vik':

**Comment by wiw4002** [comment]
Thanks!
